spring.application.name=finantel
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FINANTEL;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=admin098
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

app.jwt.keystore=classpath:finantel.p12
app.jwt.keystore-password=finantel123
app.jwt.key-alias=finantel

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

jwt.secret=123sadasdasd123123

spring.thymeleaf.cache=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
